name: Sync to Deploy Repository

on:
  push:
    branches:
      - main # ඔබේ ප්‍රධාන branch එකේ නම master නම් මෙය master ලෙස වෙනස් කරන්න

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false # අලුතින් එකතු කළ පේළිය: default bot token එක භාවිතා කිරීම නැවැත්වීමට

      - name: Push updates to Deploy Repo
        run: |
          # Git configuration සැකසීම
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # දෙවන repository එක remote එකක් ලෙස එකතු කිරීම (username එක ඉවත් කර PAT එක පමණක් ලබා දීම)
          git remote add deploy_repo https://${{ secrets.DEPLOY_PAT }}@github.com/DinukaSanjana/portfoliodeploy.git
          
          # පළමු repo එකේ main branch එක දෙවන repo එකේ main branch එකට push කිරීම
          git push deploy_repo main --force
